"""add emotion_events emotion_scores

Revision ID: 98716852523a
Revises: 554468ac1ad1
Create Date: 2026-08-30 22:26:32.758140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98716852523a'
down_revision: Union[str, None] = '554468ac1ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=24), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotion_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotion_events_source_ref_id'), ['source_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotion_events_user_id'), ['user_id'], unique=False)

    op.create_table('emotion_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('emotion', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['emotion_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotion_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotion_scores_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotion_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotion_scores_event_id'))

    op.drop_table('emotion_scores')
    with op.batch_alter_table('emotion_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotion_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_emotion_events_source_ref_id'))

    op.drop_table('emotion_events')
    # ### end Alembic commands ###
